# Generated by Django 5.2.1 on 2025-05-11 13:26

import books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=100)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("allow_comments", models.BooleanField(default=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                (
                    "book_file",
                    models.FileField(null=True, upload_to=books.models.book_file_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
