# Generated by Django 5.2.1 on 2025-05-11 17:54

import books.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=books.models.cover_image_upload_path
            ),
        ),
    ]
