/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBook: typeof import('./components/AddBook.vue)['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyncStatusBar: typeof import('./components/SyncStatusBar.vue')['default']
  }
}
